Drink 라우트 작업 및 DrinkList 컴포넌트 생성
MinQyu/Ediya-Project pull request #11
Opened 2024-03-02 08:00 UTC by MinQyu

- Drink 라우트는 스크롤이 하단에 닿을때마다 음료목록을 업데이트하고 DrinkList 컴포넌트로 보내 렌더링함
- request를 useState로 설정하고 초기값을 start:1, size: 8로 설정
- makeRequestParams()로 쿼리문을 만들고 getDrinkList()에서 https://homely-susi-hyeonqyu.koyeb.app/api/drink/list와 API 통신해 데이터를 가져옴
- 받아온 데이터를 drink 배열값만 파싱하고 drinkList에 저장. 이후에 스크롤이 하단에 닿을때마다 추가로 API 통신을 해야하므로 스프레드 연산자를 써서 기존 drinkList와 합치는 방식으로 저장
- useEffect 훅에 getDrinkList를 넣고 request.start 값을 의존성으로 설정
- request.start 값을 업데이트 하는 함수 requestUpdate()를 lodash 라이브러리의 debounce를 이용해 스크롤이 끝난 후(함수가 호출된 후) 1초의 텀으로 실행되도록 설정 -> debouncedRequestUpdate()
- 스크롤이 하단에 닿으면 debouncedRequestUpdate()를 호출하는 handleScroll()함수를 정의하고 useEffect 훅에서 이벤트 리스너 설정.
- drinkList의 프로퍼티를 파라미터로 받아 출력하는 DrinkList 컴포넌트 정의
- grid-template-columns에 repeat를 사용해 2개씩 반복해서 보여주도록 함(Drink.module.css에서 .drink_list에 정의)

2024-04-04 06:19 UTC, hyeonQyu requested changes

2024-04-04 06:19 UTC, hyeonQyu commented on src/interfaces/DrinkInterface.ts
> +export interface DDrink {
요거 타입명 확인

2024-04-04 06:19 UTC, hyeonQyu commented on src/components/DrinkList.tsx
List는 보통 배열에 붙는 suffix야
이 컴포넌트는 음료의 목록을 표현하는 컴포넌트가 아니라
음료 목록 중 하나의 요소를 나타내는 컴포넌트이기 떄문에
Drink 혹은 DrinkItem이라는 이름이 더 적절해

2024-04-04 06:19 UTC, hyeonQyu commented on src/interfaces/DrinkInterface.ts
> +export interface DrinkData {
엄밀하게 말하면 Data, Info 이런 이름도 좋지 않아. 있으나 마나한 말이거든
여기서는 DrinkResponse가 가장 적절한 이름으로 보여

2024-04-04 06:19 UTC, hyeonQyu commented on src/route/Drink.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
loading은 false로 시작해서 api 요청 직전에 true로 바뀌는 것이 맞음

2024-04-04 06:19 UTC, hyeonQyu commented on src/route/Drink.tsx
> +    }));
size는 바뀌지 않는 값인데 상태로 관리될 필요가 있을까??
start 값만 상태로 관리해도 될 것처럼 보임

2024-04-04 06:19 UTC, hyeonQyu commented on src/route/Drink.tsx
> +  function handleScroll() {
여긴 왜 갑자기 뜬금없이 function 키워드가 나왔지?

2024-04-07 10:12 UTC, MinQyu commented on src/interfaces/DrinkInterface.ts
> +export interface DDrink {
- DrinkType으로 변경

2024-04-07 10:13 UTC, MinQyu commented on src/components/DrinkList.tsx
- DrinkItem으로 변경

2024-04-07 10:13 UTC, MinQyu commented on src/interfaces/DrinkInterface.ts
> +export interface DrinkData {
- DrinkResponse로 변경

2024-04-07 10:17 UTC, MinQyu commented on src/route/Drink.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
- loading을 api 통신시에만 true가 되도록 바꾸고, 스크롤 이벤트 리스너를 로딩 상태일 때만 추가하도록 함

```typescript
  useEffect(() => {
    if (!loading) window.addEventListener("scroll", handleScroll);
    else
      return () => {
        window.removeEventListener("scroll", handleScroll);
      };
  }, [loading]);
```

2024-04-07 10:18 UTC, MinQyu commented on src/route/Drink.tsx
> +    }));
- size는 상태변수로 관리하지 않고 상수로 선언함

2024-04-07 10:20 UTC, MinQyu commented on src/route/Drink.tsx
> +  function handleScroll() {
- 디바운스 예제 보면서 하다가 쓴듯함.  화살표 함수로 수정

2024-04-11 06:56 UTC, hyeonQyu commented on src/interfaces/DrinkInterface.ts
> +export interface DDrink {
DrinkType이란 이름도 마찬가지로 적절한 이름은 아님
보통 Type이 뒤에 붙게 되는 경우는 음료에 대한 타입이 커피인지, 주스인지 등을 구분할 때
type DrinkType = 'coffee' | 'juice'; 이런 식으로 많이 사용함
일단 여기서는 넘어가는거로

2024-04-11 06:57 UTC, hyeonQyu commented on src/route/Drink.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
응? 이렇게 되면 loading 상태가 변할때마다 이벤트 등록 및 해제가 일어나는데 왜 이렇게 한건지??

2024-04-11 06:58 UTC, hyeonQyu commented on src/route/Drink.tsx
> +    }));
보통 이런 상수는 전부 대문자로 쓰는게 일반적이야
예: REQUEST_SIZE

2024-04-11 06:59 UTC, hyeonQyu commented on src/route/Drink.tsx
> +    }));
prevRequest는 이제 start값만 존재하므로 굳이 객체로 존재할 필요는 없음
다만 나중에 확장성을 고려하여(start 외 다른 request 값이 추가될 수 있는 경우) 냅둘수도 있음

2024-04-11 08:19 UTC, MinQyu commented on src/route/Drink.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
loading 상태관리의 목적이 api 통신중일때 추가로 api 통신을 요청하는 것을 막기 위함이기 때문

2024-04-11 08:35 UTC, MinQyu commented on src/route/Drink.tsx
> +    }));
상수명 REQUEST_SIZE로 변경

2024-04-15 05:25 UTC, hyeonQyu commented on src/route/Drink.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
그럼 말한대로 loading 상태가 변할때마다 이벤트 등록 및 해제가 발생해
api 통신을 막는거는 여기가 아니라 다른 곳에서 해줘야 맞는거임

2024-05-03 08:34 UTC, merged