DrinkDetail 모달 추가
MinQyu/Ediya-Project pull request #13
Opened 2024-03-03 12:49 UTC by MinQyu

- 음료 목록 클릭시 sn 값으로 음료 정보를 받아와 모달을 띄우는 DrinkDetail 컴포넌트 생성
- 모달은 DrinkList 컴포넌트에서 호출하며, isModalOpen으로 상태를 관리함
- openModal로 모달을 열고 closeModal로 모달을 닫음. 모달이 열릴시 스크롤 바를 숨김
- 모달은 esc키를 눌렀을 때 닫혀야하므로 onKeyDown 이벤트 핸들러를 사용해 키보드 버튼을 누를 시 handleEscape 함수가 실행되도록 함
- handleEscape는 키코드가 'esc'이면 closeModal을 호출
- DrinkDetail에 Drink 라우트로부터 받았던 sn 값과, 모달을 닫는 함수 closeModal을 전달
- DrinkDetail은 sn 값을 이용해 https://homely-susi-hyeonqyu.koyeb.app/api/drink/detail에서 음료의 세부 정보를 받아옴
- 화면을 덮는 오버레이를 생성하고 모달을 출력. 오버레이 클릭시 모달이 닫히게 만들고 싶었는데, handleClose를 실행시켜 DrinkList에서 전달받은 onClose() 함수를 호출해도 isModalOpen이 바뀌지 않음. 원인을 찾지 못함
- 
![모달](https://github.com/MinQyu/Ediya-Project/assets/78997415/bfb56140-9afa-4e2e-8ebc-ddf3064601dd)

2024-04-11 10:12 UTC, hyeonQyu requested changes

2024-04-11 10:12 UTC, hyeonQyu commented on src/components/DrinkDetail.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
기본값 false

2024-04-11 10:12 UTC, hyeonQyu commented on src/components/DrinkDetail.tsx
> +            <h3>{drinkDetail && drinkDetail.title}</h3>
drinkDetail이 있는지 계속 확인하는데 한번만 확인하도록 수정할 수 있을듯

2024-04-11 10:12 UTC, hyeonQyu commented on src/components/DrinkList.tsx
> +    if (event.keyCode === 27) {
event.key 값을 사용하면 27보다 좀 더 직관적인 값으로 키 이벤트를 처리할 수 있어

2024-04-13 07:04 UTC, MinQyu commented on src/components/DrinkDetail.tsx
> +            <h3>{drinkDetail && drinkDetail.title}</h3>
https://github.com/MinQyu/Ediya-Project/pull/21 여기서 수정

2024-04-13 09:44 UTC, MinQyu commented on src/components/DrinkList.tsx
> +    if (event.keyCode === 27) {
- https://github.com/MinQyu/Ediya-Project/pull/21 에서 수정
```typescript
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
```

2024-04-15 06:02 UTC, hyeonQyu approved these changes

2024-05-03 08:51 UTC, merged