헤더 컴포넌트 생성
MinQyu/Ediya-Project pull request #2
Opened 2024-02-21 22:23 UTC by MinQyu

모든 라우트에서 사용될 헤더 컴포넌트와 css 파일 생성.
로고 이미지 클릭시 홈으로 이동, '이디야 음료' 클릭시 /drink 페이지로 이동, '이디야 뉴스' 클릭시 /News 페이지로 이동함.

2024-02-22 13:36 UTC, hyeonQyu commented
담부턴 이미지도 같이 캡처해

2024-02-22 13:45 UTC, hyeonQyu requested changes

2024-02-22 13:45 UTC, hyeonQyu commented on src/components/Header.module.css
> +  height: Hug(22px);
Hug는 뭐임?

2024-02-22 13:45 UTC, hyeonQyu commented on src/components/Header.module.css
헤더 안의 내용이 디자인과 다르게 가운데로 안오고있지? 가운데로 올 수 있게 바꿔봐

2024-02-22 13:45 UTC, hyeonQyu commented on src/components/Header.tsx
> +    <div className={styles.header}>
헤더는 div 태그보다 header 태그를 사용하는게 좋음

2024-02-22 13:45 UTC, hyeonQyu commented on src/components/Header.tsx
> +      <div className={styles.menu}>
이런 경우 menu는 `<ul>` 태그(unordered list)를 사용하고
각 item은 `<li>` 태그(list item)를 사용하는게 적절함

2024-02-22 13:45 UTC, hyeonQyu commented on src/image/logo.png
이미지 파일은 src 폴더가 아닌 public 폴더 하위로 들어가야함
public 폴더에 assets 폴더를 만들고 그 안에서 관리하는 구조로 바꿔

2024-02-22 13:45 UTC, hyeonQyu commented on src/route/Home.tsx
> +        <Header />
아마 홈 화면에서만 헤더를 사용하지는 않을거임
헤더, 푸터같은 경우는 기본적으로 거의 모든 페이지에 들어가는 레이아웃인데
이 레이아웃을 모든 페이지에 각각 불러와서 쓰는거보다 더 좋은 방법이 있겠지?

2024-02-23 10:57 UTC, MinQyu reviewed
- Hug는 피그마에서 copy 눌러서 레이아웃 복사하면 그렇게 뜨던데 css에서 지우나 넣으나 똑같더라고. 코멘트가 resolve conversation 눌렀더니 사라졌어;;

- Header와 이후 추가할 Footer는 페이지가 바뀌어도 항상 렌더링되어야함. Layout 컴포넌트를 만들고 App 컴포넌트에서 각 라우트들을 감쌈. Header는 Layout 컴포넌트에서 호출  Footer도 Laycout 컴포넌트에 넣을 예정

- Layout 컴포넌트의 프로퍼티 타입 정의를 위해 interface.ts 파일 생성.

- 헤더가 피그마의 디자인이랑 일치하도록 css 수정

- 이미지 경로 public/assets로 수정

2024-03-04 13:46 UTC, hyeonQyu commented
레이아웃의 프로퍼티 타입 정의를 왜 interface.ts에 했는지 궁금

2024-03-04 13:46 UTC, hyeonQyu approved these changes

2024-03-04 15:21 UTC, merged