intro컴포넌트 생성
MinQyu/Ediya-Project pull request #4
Opened 2024-02-23 14:31 UTC by MinQyu

- api 통신으로 동영상의 url을 string 형태로 받아와 ID를 분리한 뒤, <iframe> 태그를 이용해 유튜브 동영상을 출력
- 회색 배경을 넣기 위해 Home.module.css 파일을 추가

2024-02-23 14:39 UTC, MinQyu reviewed
- promotion의 position값 조정
![인트로](https://github.com/MinQyu/Ediya-Project/assets/78997415/53fc2428-7fa6-4df3-a504-7b455cd6b38d)

2024-03-08 13:22 UTC, hyeonQyu requested changes

2024-03-08 13:22 UTC, hyeonQyu commented on src/components/Intro.tsx
> +    ></iframe>
프리티어에서 이부분 안잡아주나?
<iframe /> 이렇게 닫아줄텐데

2024-03-08 13:22 UTC, hyeonQyu commented on src/components/Intro.tsx
> +  const [introId, setIntroId] = useState<string>("");
이거는 엄청 중요한 내용은 아니고 가볍게 지나가도 될만한 팁인데
`useState<string>("")` 이렇게 쓴거를 `useState("")` 이렇게 쓰더라도 introId를 string 타입으로 인식함
`useState<string>()` 이렇게 썼다면 introId는 string | undefined 타입으로 인식하게 됨

이제 중요한건 아래에 쓰는 내용인데
너는 지금 introId를 받아오지 않은 경우에 빈 문자열로 두고 있는데
이게 문제가 될 수 있는 부분은
이렇게 간단한 어플리케이션이 아니라 좀 복잡한 형태인 경우에
introId가 string 상태의 값을 갖고 있기 때문에 이게 유효하지 않은 값임에도 불구하고 누군가는 유효한 값이라고 착각을 할 수 있다는 점이야.
무슨 말이냐면 introId가 undefined인 경우에는 대부분의 사람들이 introId가 아직 할당되기 전이기 때문에 유효하지 않은 값이라고 생각하지만
introId가 string인 경우 이게 컴파일 타임(타입 체킹 시점, 런타임 말고)에 유효한 값이라고 판단할 수도 있다는 것이지. introId가 ""인지 "1234"인지는 런타임에 알 수 있는거니까
그러면 원하지 않는 방식으로 동작을 할 여지도 생길 수 있는거야.

잘 이해가 안될수도 있는데 이해 안되면 전화해 다시 설명해줄게

2024-03-08 13:55 UTC, hyeonQyu requested changes
고쳐보자

2024-03-08 14:49 UTC, MinQyu reviewed
- introId를 string 값("")으로 초기화하지 않고, introId의 값이 할당되었을때 <iframe>이 렌더링되도록 수정

2024-03-12 08:00 UTC, hyeonQyu commented on src/components/Intro.tsx
> +      )}
이부분은 다음과 같은 리액트 조건부 렌더링을 쓰면 됨
```typescript
{introId && (
        <iframe
          title="Intro"
          width="100%"
          height="100%"
          frameBorder="0"
          src={`https://www.youtube.com/embed/${introId}`}
        />
```

2024-03-12 08:00 UTC, hyeonQyu commented on src/components/Intro.tsx
> +      )}
이렇게 수정한 뒤 머지

2024-03-12 08:00 UTC, hyeonQyu approved these changes

2024-03-12 08:25 UTC, merged