notice컴포넌트 생성
MinQyu/Ediya-Project pull request #5
Opened 2024-02-24 09:39 UTC by MinQyu

- 좌, 우 버튼으로 조작 가능한 공지사항을 출력하는 Notice 컴포넌트 생성 
- https://homely-susi-hyeonqyu.koyeb.app/api/notice 에서 API 통신을 통해 json을 받아오고, 파싱해서 프로퍼티를 원래의 타입으로 변환
- 타입은 interface.ts 파일에 NoticeData로 정의
- API 통신함수 getNoticeList는 의존성 없이 useEffect 훅에 넣어 렌더링시에만 호출
- API 통신을 기다리기 위한 loading, setLoading을 useState로 선언
- NoticeList 의 인덱스 조작을 위한 noticeIndex, setNoticeIndex를 useState로 선언
- 버튼을 클릭시 실행할 noticePrev, noticeNext 함수 정의
- NoticeList의 Date 타입 프로퍼티 registrationDate의 출력을 위한 formatDate 함수 정의. 출력 형태는 YYYY.MM.DD

- 버튼은 NoticeList의 첫 인덱스일 경우 좌측 버튼이, 마지막 인덱스일 경우 우측 버튼이 비활성화 되도록 설정
- 버튼 내부의 '<', '>' 모양 UI는 피그마에서 모양 보고 svg 태그로 그렸는데, 피그마에서 svg 파일로 export 가능한걸 이 풀리퀘 디스크립션 쓰다가 알게됨..
- NoticeList.content의 글자 수가 45 이상이면 slice해서 '...'와 함께 출력
- 공지사항 내용 클릭시 /News 페이지로 이동
-
![notice](https://github.com/MinQyu/Ediya-Project/assets/78997415/492decdc-fc57-4233-a4bb-2e8c69d3a4d0)

2024-03-08 13:52 UTC, hyeonQyu requested changes

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +    const parsedJson = parseNoticeJson(json);
eslint 설정을 했으면 아마 잡아줬을거 같은데.. vscode에서도 충분히 잡아줄거같은데
parseNoticeJson 함수는 인자로 NoticeData[] 타입을 받고 있어.
근데 여기서 너가 전달한 json의 타입은 뭘까? 이렇게 사용하면 타입스크립트를 사용하는 의미가 없어짐
너가 받는 인자의 타입과 전달하는 인자의 타입이 일치해야지

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +  const [loading, setLoading] = useState<boolean>(true);
loading 상태가 처음부터 true인게 맞을까? 아니면 API 호출을 시작하는 시점부터 true가 되는게 맞을까?

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +  const parseNoticeJson = (json: NoticeData[]): NoticeData[] => {
받는 타입부터 정확하지 않음. json이 NoticeData[] 형태가 정확히 맞을까?
그게 맞다면 NoticeData[] 타입을 NoticeData[] 타입으로 변환하는건데
그럼 변환과정이 의미 없지 않겠어? 타입이 다르니까 변환하는거 아니야?

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +  const noticePrev = () => {
함수 이름은 동사형태로 짓는게 좋음

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +    if (noticeIndex > 0) setNoticeIndex(noticeIndex - 1);
이건 리액트에서 초보자들이 하기 제일 쉬운 실수중에 하나인데
너는 지금 noticeIndex의 상태를 보고 noticeIndex 상태를 변경했잖아?
근데 이 if문 안에 있는 noticeIndex가 **최신 상태가 아닐 수 있어**. (**아닐 수가 있다**는 것은 **맞을 수도 있다**는 뜻. 프로그래밍에서 **잘 작동하지 않는 것**은 디버깅해서 고치면 되지만, **잘 작동할 수도 있고 않을 수도 있다는 것**은 디버깅하기 굉장히 어려운 부분이지. 그래서 **잘 작동하지 않는 것보다 더 안좋은거**야)
이건 리액트의 setState가 **비동기적**으로 동작하기 때문이야(비동기라는 개념을 모르면 꼭 공부해야함, 나한테 질문하던지)
나도 입문 시절에 리액트의 이런 특성때문에 삽질한적 있었음.
아래 글을 꼭 읽어보고 수정해봐
https://parkparkpark.tistory.com/163

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +  };
이 formatDate는 여러군데에서 쓰일 것 같으니 여기보다는 밖에 따로 빠져 있는게 코드 재사용 측면에서 좋겠다.
내가 이후 PR은 아직 못봤지만 너가 이후에 그렇게 했을 수도 있을 것 같고. 만약 이후 PR에서 그렇게 했다면 여기서 수정 안해도 됨

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +              <svg width="10" height="10" viewBox="0 0 10 10">
요거는 왼쪽 오른쪽 두개 있잖아
그러면 svg 하나를 하나의 컴포넌트로 빼서 왼쪽, 오른쪽일 때 방향만 돌려주면 되지 않을까?
설령 그렇지 않더라도 하나의 컴포넌트로 빼는게 맞아보이는게
너무 뜬금없이 svg가 있어서 이게 무슨 그림인지 코드만 보고 알기가 어려움
그치만 svg를 ArrowIcon이라는 컴포넌트로 뺐다면 화살표 모양의 아이콘이구나 하고 직관적으로 알 수 있겠지?

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +              <h3>{noticeList && noticeList[noticeIndex].title}</h3>
`noticeList[noticeIndex].xxx`라는 코드가 계속해서 들어가고 있어
이렇게 하는것보다
`const currentNotice = noticeList[noticeIndex];` 이렇게 선언해서 사용하는게 더 좋은 방식이야.
경우에 따라서는
`const { title, registrationDate, content } = noticeList[noticeIndex];` 이렇게 구조분해할당을 사용할 수도 있어.

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +                    ? `${noticeList[noticeIndex].content.slice(0, 45)}...`
45는 어디서 나온 수치인걸까?

2024-03-08 13:52 UTC, hyeonQyu commented on src/components/Notice.tsx
> +                    ? `${noticeList[noticeIndex].content.slice(0, 45)}...`
난 ... 구현을 js 코드가 아닌 css로 구현하면 좋겠어

2024-03-08 13:57 UTC, hyeonQyu requested changes
내가 많이 달았는데
지적한 것 중에서 너가 이후 PR에서 이미 고쳐놓은거는 여기서 고칠 필요 없고
댓글로 다른 PR에서 반영했다고 남기고 그 PR 링크만 적어놓으면 돼

2024-03-09 09:27 UTC, MinQyu reviewed
- API 통신 후 받은 json의 registrationDate의 타입은 string임. ResponseNoticeData 인터페이스를 새로 정의하고 파싱 이후에 Date 타입의 registrationDate을 가진 NoticeData 형식이 되도록 수정
- 리턴문에서의 loading상태 사용 방식상 loading의 초기값을 설정하지 않으면 렌더링이 되지 않았음. API 호출 이후 상태를 보장하기 위해 loading을 사용했지만, getNoticeList는 여러번 호출하지 않으니 리턴문에서 초기값을 설정하지 않은 noticeList를 검사해도 동일한 상태를 보장할 수 있어 noticeList를 검사하도록 수정
- noticePrev, noticeNext 함수 이름 수정 -> goPrev, goNext
- noticeIndex는 비동기적으로 업데이트됨. 처음에 링크의 글을 참고해서 고쳐봄. noticeIndex를 검사시 최신 상태임을 보장하기 위해 새로운 indexDirection을 useState 훅에 선언하고 goPrev에선 indexDirection을 true로, goNext에선 false로 만들도록 했음.  그리고 useEffect에서 indexDirection와 noticeIndex를 의존성으로 넣고 indexDirection이 true면서 endIndex보다 작으면 noticeIndex를 +1을 하고, false면서 0보다 작으면 noticeIndex를 -1을 하도록 만들었음. 그런데 이렇게하면 noticeIndex가 바뀔때도 인덱스 증감이 일어나서 다른 방법을 찾아봄. REACT HOOK API 문서를 보다가 useCallback을 발견함. 이건 함수 자체에 의존성을 넣어 noticeIndex가 바뀔떄만 함수 인스턴스를 생성하는 방식이이라 원하는 기능을 구현할 수 있었음. 
- formatDate를 src/utils/dateUtil.ts에 따로 정의. getMonth시에 +1 안한것도 발견해서 수정
- currentNotice 어디에 선언해서 상태관리를 어떻게 해야하는지 감이 안잡혀. 저거는 설명을 들어야할거같아
- 말줄임표를 overflow : hidden과 text-overflow : ellipsis으로 구현하도록 수정. 그런데 content 부분은 말줄임표 출력이 안됨. 이유를 잘 모르겠음

2024-03-12 08:01 UTC, hyeonQyu commented
보기 어려우니 담부터는 웬만하면 내가 단 댓글에 답글로 남겨줘
또 저렇게 한번에 쓰면 내가 하나하나 따로 답글 달기가 어렵잖아?

2024-03-12 08:04 UTC, hyeonQyu commented
리뷰는 이따 집가서...

2024-03-16 14:03 UTC, hyeonQyu commented on src/interfaces/interface.ts
>  }
```typescript
export interface NoticeData extends Omit<ResponseNoticeData, 'registrationDate'> {
   registrationDate: Date;
}

type NoticeData =  Omit<ResponseNoticeData, 'registrationDate'> & {
   registrationDate: Date;
}

Omit<ResponseNoticeData, 'registrationDate'> = Pick<ResponseNoticeData, 'index' | 'title' | 'content'>= {
  index: number;
  title: string;
  content: string;
}
```
Pick<ResponseNoticeData, 'index' | 'title' | 'content'>

2024-03-16 14:14 UTC, hyeonQyu commented on src/components/Notice.tsx
> +  }, [noticeIndex]);
```typescript
const noticeNext = () => {
    if (noticeIndex < endIndex) setNoticeIndex(noticeIndex + 1);
   setNoticeIndex((prevIndex) => {
        if(prevIndex < endIndex) return prevIndex + 1;
       return prevIndex;
    })
    setNoticeIndex((prevIndex) => prevIndex < endIndex ? prevIndex + 1 : prevIndex);
};
```

2024-03-17 11:42 UTC, MinQyu commented on src/components/Notice.tsx
> +  }, [noticeIndex]);
setNoticeIndex에서 이전 상태를 참조하고 인덱스를 변경하도록 수정

2024-03-17 11:51 UTC, MinQyu commented on src/interfaces/interface.ts
>  }
- NoticeData는 Omit을 통해 registrationDate을 제외한 ResponseNoticeData의 속성을 상속받도록 함
- 파싱시에도 같은 속성은 그대로 사용하도록 변경

```typescript
export interface ResponseNoticeData {
  index: number;
  title: string;
  content: string;
  registrationDate: string;
}

export interface NoticeData
  extends Omit<ResponseNoticeData, "registrationDate"> {
  registrationDate: Date;
}

 const parseNoticeJson = (json: ResponseNoticeData[]): NoticeData[] => {
   return json.map((notice) => ({
     ...notice,
     registrationDate: new Date(notice.registrationDate)
   }));
 };
```

2024-03-26 06:55 UTC, hyeonQyu approved these changes

2024-03-26 08:23 UTC, merged