article컴포넌트 생성
MinQyu/Ediya-Project pull request #6
Opened 2024-02-25 14:26 UTC by MinQyu

- api 통신으로 기사 데이터를 받아 최신기사 2개를 출력하는 article 컴포넌트 생성
- registrationDate를 Date 타입으로 파싱
- 타입은 interface.ts 파일에 Articles, Paging, 두 개를 합친 ArticleData로 정의
- makeRequest으로 쿼리문을 만들어 API 호출
- lastPage는 25이지만 기사가 있는 마지막 페이지는 24라서 currentPage = 24로 불러옴
- 뉴스 페이지로 이동하는 '+'모양 버튼 내 이미지는 피그마에서 svg 파일로 받아와 사용
- 기사는 날짜 역순으로 정렬되어 있어 articleList.articles의 마지막 요소와 그 전 요소를 출력
- notice를 만들때는 일정 글자 수 이상이면 자르도록 코드를 짰는데, 피그마에서 길이가 다른 두 기사 제목이 같은 길이로 잘려있는 것을 보고 찾아보다가 overflow: hidden, text-overflow: ellipsis 속성을 알게됨

2024-03-26 07:11 UTC, hyeonQyu requested changes

2024-03-26 07:11 UTC, hyeonQyu commented on src/components/Ariticle.tsx
> +        <div>loading..</div>
이렇게 로딩 상태를 표시하는 방법도 맞지만
React Suspense라는걸 사용해서 한번 해보면 좋을듯

이 내용은 여기서 수정 안해도 되고 별도 PR로 올려서 해봐

2024-03-26 07:11 UTC, hyeonQyu commented on src/components/Ariticle.tsx
> +  const [articleList, setArticleList] = useState<ArticleData>();
articleList라는 이름이 어울릴까? list라는 이름 때문에 배열처럼 느껴지는데

2024-03-26 07:11 UTC, hyeonQyu commented on src/components/Ariticle.tsx
> +    };
paging은 그냥 json.paging이랑 같아보이는데

2024-03-26 07:11 UTC, hyeonQyu commented on src/components/Ariticle.tsx
> +  };
이건 이전에 공통 유틸로 옮겼던거같은데 아직 여기엔 반영이 안된건가??

2024-03-26 07:11 UTC, hyeonQyu commented on src/components/Ariticle.tsx
> +                  )}
첫째 뉴스와 둘째 뉴스 그리는거에서 코드 중복이 보이지? 이럴때 컴포넌트로 분리할 수도 있고, 2개를 배열로 만들어서 map을 돌리는 방법으로 코드 중복을 없앨 수 있어

2024-03-28 08:59 UTC, MinQyu commented on src/components/Ariticle.tsx
> +  const [articleList, setArticleList] = useState<ArticleData>();
- articleData로 변경

2024-03-28 09:02 UTC, MinQyu commented on src/components/Ariticle.tsx
> +    };
- 인터페이스와 파싱함수 수정
```typescript
  const parseArticleJson = (json: {
    articles: ResponseArticles[];
    paging: Paging;
  }): ArticleData => {
    const articles: Articles[] = json.articles.map(
      (article: ResponseArticles) => ({
        ...article,
        registrationDate: new Date(article.registrationDate)
      })
    );
    const paging: Paging = {
      ...json.paging
    };
    return { articles, paging };
  };
```

2024-03-28 09:03 UTC, MinQyu commented on src/components/Ariticle.tsx
> +  };
- 브랜치를 업데이트하고 유틸 파일에서 formatDate를 불러와 사용하도록 수정

2024-03-28 09:07 UTC, MinQyu commented on src/components/Ariticle.tsx
> +                  )}
- articleData를 마지막 두 개만 자르고 map을 이용해 출력하도록 수정
```typescript
          <div className={styles.article_content_wrap}>
            {articleData &&
              articleData.articles.slice(-2).map((article) => {
                return (
                  <div className={styles.article_content}>
                    <p className={styles.article_content__title}>
                      {article.title}
                    </p>
                    <p className={styles.article_content__date}>
                      {formatDate(article.registrationDate)}
                    </p>
                  </div>
                );
              })}
          </div>
```

2024-04-04 05:24 UTC, hyeonQyu approved these changes

2024-04-04 14:24 UTC, merged